# Generated by Django 4.0.3 on 2022-06-17 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CategorieAnnonce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnonceVoiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomVoiture', models.CharField(max_length=255, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image', models.TextField(blank=True, db_column='data', null=True)),
                ('activationAnnonce', models.BooleanField(default=False)),
                ('annoceWNScrappOfAdmin', models.BooleanField(default=False)),
                ('typeCar', models.CharField(max_length=255, null=True)),
                ('emailUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
                ('idVoiture', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='CategorieAnnonce.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Concessionnaires',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomConcessionnaires', models.CharField(max_length=255, null=True)),
                ('Tel', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('nomMarque', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('imageMarque', models.TextField(blank=True, db_column='data', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendeurPro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255, null=True)),
                ('Tel', models.CharField(max_length=50, null=True)),
                ('Fax', models.CharField(max_length=50, null=True)),
                ('image', models.TextField(blank=True, db_column='data', null=True)),
                ('nomVendeur', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoitureNeuf',
            fields=[
                ('annonceVoiture', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='automobilewebscrapper.annoncevoiture')),
                ('disponible', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoitureOccasion',
            fields=[
                ('annonceVoiture', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='automobilewebscrapper.annoncevoiture')),
                ('description', models.CharField(max_length=1000, null=True)),
                ('annee', models.CharField(max_length=4, null=True)),
                ('KMS', models.IntegerField(null=True)),
                ('localite', models.CharField(max_length=255, null=True)),
                ('energie', models.CharField(max_length=255, null=True)),
                ('boiteVitesse', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='annoncevoiture',
            name='nomMarque',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='automobilewebscrapper.marque'),
        ),
    ]
