# Generated by Django 4.0.3 on 2022-06-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobilewebscrapper', '0002_alter_annoncevoiture_emailuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Concessionnaires',
        ),
        migrations.DeleteModel(
            name='VendeurPro',
        ),
    ]
