# Generated by Django 4.0.3 on 2022-06-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('idNotification', models.AutoField(primary_key=True, serialize=False)),
                ('emailAdmin', models.CharField(max_length=255, null=True)),
                ('emailMembre', models.CharField(max_length=255, null=True)),
                ('contenu', models.CharField(max_length=255, null=True)),
                ('dateNotification', models.DateField(null=True)),
            ],
        ),
    ]
