# Generated by Django 4.0.3 on 2022-06-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('nomCategorie', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('activationCategorie', models.BooleanField(default=False)),
            ],
        ),
    ]
